/*
 * The project master branch is automatically checked out from GitHub repo into the Jenkins workspace.
 * This pipeline script checks there is no compilation errors across the project and then runs JUnit tests.
 * It's worth noting that the JUnit tests all run twice as TestSuite.java is also executed during JUnit test stage.
 * Several Jenkins plugins are required to run this such as:
 * 	- All default suggested plugins
 *  - Maven Integration plugin
 *  - Pipeline Maven Integration Plugin
 *  - JUnit Attachments Plugin
 * Also, Jenkins should be using Java 8 (JDK 8) in it's global and system configuration.
*/

pipeline {
  agent any
  stages {
    stage('Build / Compile') {
      steps {
        withMaven(maven : 'Maven3') {
          //Goes into the TextAnalyserTool folder as this is where POM.xml is stored.
          dir("TextAnalyserTool") {
            bat 'mvn clean compile'
          }
        }
      }
    }
    stage('JUnit Tests') {
      steps {
        withMaven(maven : 'Maven3') {
          dir("TextAnalyserTool") {
            bat 'mvn test'
          }
        }
      }
    }
    stage('SonarQube Analysis') {
      environment {
        SCANNER_HOME = tool 'SonarQubeScanner'
      }
      steps {
        withSonarQubeEnv('SonarQubeServer') {
          dir("TextAnalyserTool") {
            bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.3:sonar'
          }
		}
	  }
    }
  }
}
